export const CATEGORIES = ['Electronics', 'Clothing', 'Beauty', 'Home', 'Outdoors'];

export const PRODUCTS = [
  {
    id: 'smartphone-01',
    title: 'Nimbus Smartphone',
    category: 'Electronics',
    price: 699,
    rating: 4.7,
    description: 'A sleek mobile designed for modern productivity and immersive media.',
    image: '/vite.svg',
    badges: ['Best seller', 'Fast charging'],
  },
  {
    id: 'headphones-02',
    title: 'Phase Noise Cancelling Headphones',
    category: 'Electronics',
    price: 189,
    rating: 4.4,
    description: 'Comfortable over-ear audio with deep bass and noise isolation.',
    image: '/vite.svg',
    badges: ['Free shipping'],
  },
  {
    id: 'jacket-01',
    title: 'Aurora Windbreaker',
    category: 'Clothing',
    price: 129,
    rating: 4.6,
    description: 'Lightweight jacket built for trail runs, walks, and everyday wear.',
    image: '/vite.svg',
    badges: ['New arrival'],
  },
  {
    id: 'candles-01',
    title: 'Wellness Scented Candle Set',
    category: 'Home',
    price: 42,
    rating: 4.3,
    description: 'A calming candle trio with notes of lavender and sandalwood.',
    image: '/vite.svg',
    badges: ['Gift ready'],
  },
  {
    id: 'backpack-01',
    title: 'Trailblazer Backpack',
    category: 'Outdoors',
    price: 89,
    rating: 4.5,
    description: 'Durable pack with plenty of space for day trips and everyday carry.',
    image: '/vite.svg',
    badges: ['Durable build'],
  },
  {
    id: 'skincare-01',
    title: 'Glow Radiance Set',
    category: 'Beauty',
    price: 56,
    rating: 4.2,
    description: 'A gentle skincare kit with toner, serum, and moisturiser.',
    image: '/vite.svg',
    badges: ['Cruelty free'],
  },
];
